flathub/com.slack.Slack

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> Update to 3.1.0

com.slack.Slack.appdata.xml
Mention that this is not supported by slack, and tweak what icon to use.
=> Appdata tweaks

com.slack.Slack.appdata.xml, com.slack.Slack.json
https://github.com/flathub/com.slack.Slack/issues/27
=> Update to 3.3.7

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> Update to 3.3.8

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> Update to 3.4.0

com.slack.Slack.json
=> Fix goof in desktop edit

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> Update to 4.0.0

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> Update to 4.0.1

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> Update to 4.0.2

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> Update to 4.1.1

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> Update to 4.3.2

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> Update to 4.4.0

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> update to 4.4.2

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> update to 4.4.3

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> update to 4.7.0

com.slack.Slack.appdata.xml, com.slack.Slack.json
=> update to 4.8.0

com.slack.Slack.json
https://github.com/flathub/com.slack.Slack/issues/130
=> Set is-main-source to true

com.slack.Slack.json
=> Update url pattern

com.slack.Slack.appdata.xml
- ~enable `WaylandWindowDecorations` feature for showing window-decorations~
- fix screenshot asset link to fix build
=> Update screenshot asset link

com.slack.Slack.json
We switched from GNU ar to bsdtar in f8f31db
=> Don't install GNU ar to Flatpak

com.slack.Slack.yaml
=> Bump base & runtime versions to 24.08
