flathub/com.slack.Slack

- com.slack.Slack.json
Freedesktop 18.08 works with multi-arch, so libraries are split out,
and libbfd has moved. This patch updates the copying of libbfd to
the new multi-arch system.
Obviously don't merge until freedesktop released as stable
Note: this is not backwards compatible with 1.6 as /usr/lib/{multiarch-triple}/libbfd.so doesn't exist in 1.6
> Patch to work with freedesktop 18.08

- com.slack.Slack.json
- slack.desktop
There seems to be some issue with installing the desktop file from `extra_data` so add it to source tree.
Also use `desktop-file-edit` instead of `sed`.
> Add desktop file directly

- com.slack.Slack.json
zypak is part of electron2 base app now.
> Don't bundle zypak

- com.slack.Slack.json
Currently, the application doesn't register the menu into my desktop environment, so I added an additional finish-arg as it was stated in [Octave issue](https://github.com/flathub/org.octave.Octave/issues/6)
> Register application menu into desktop environment

- com.slack.Slack.json
Add pipewire screen sharing support following chromium flatpak's example. Pipewire is necessary to get screen sharing with chromium on wayland, and works correctly now in flatpak with these changes. The feature works fairly well, aside from some relatively minor bugs. The core screen sharing functionality works and is stable.
This PR builds the pipewire module with the flatpak, and also adds a needed chromium pipewire flag to the .desktop file. This feature works out of the box with these fixes, and no manual configuration or flags are needed from end users. This addition does not regress more traditional screen sharing in x11, it should only improve the experience for wayland users (tested on fedora 34 and ubuntu 20.04, on wayland and x11).
Fixes #101
Current issues with this …
> Build with pipewire support to enable wayland screen sharing

- com.slack.Slack.json
Also include a x-data-checker config. The only thing that can be considered lacklustre is the discarding of the udev rules, but then again Slack is an application with full device access anyway.
@barthalion Sorry for bothering you so much today, but who is actually in charge of application bundles like these?
> Update pipewire to latest version

- com.slack.Slack.json
@barthalion Hey, after this afternoon's incident, I've looked into the source-url and found a possibly better source: This is the one that they directly link on their website. I'm not sure what the impact will be if we change this in the long run, but at this time the files are identical so that's good.
As for the x-data-checker, I hope it works because webpage-scraping is always hit-and-miss.
> Use an alternative data-source as defined by main project

- com.slack.Slack.json
This isn't necessary in the first place as PipeWire 0.3.x is included in the 20.08 FreeDesktop runtime. [Chromium Flatpak uses PipeWire included in the runtime](https://github.com/flathub/org.chromium.Chromium/blob/master/org.chromium.Chromium.yaml) and screen sharing works.
In the past we needed to add PipeWire 0.2.x as Electron<13 defaulted to only have support for PipeWire 0.2.x for screen sharing on Wayland.
According to Slack's logs (accessible via DEB/RPM) Slack should be on Electron 13/Chromium 91, so we no longer need to add PipeWire 0.2.x like in https://github.com/flathub/com.slack.Slack/pull/118.
We should still test screen sharing on Wayland though. If anyone has a paid Slack account (necessary for screen sharing) please test this branch.
See …
> Remove PipeWire 0.3.x module

- com.slack.Slack.json
Currently when running on Wayland, slack will fall back to XWayland which results in blurry rendering (if it runs at all). There is no way to configure Slack to run on Wayland
This change forces Slack to run naively on Wayland but only if that's the only an option. That is, it'll only run on Wayland if the user configurs the overrides `sockets=wayland;!x11`.
> Run natively on Wayland when available

- com.slack.Slack.json
Previously, `flatpak-external-data-checker` was failing due to the `is-main-source` flag not being a boolean.
> Fix automatic updates due to is-main-source not being boolean

- com.slack.Slack.json
* Revert wayland by default (fixes #212, #211, #210)
* Address missing dbus permissions. Slack now requires access to session secrets manager and system login dbus interfaces. Add `xdg-download` permissions to fix file downloads not appearing in the download folder (fixes #202, #193)
* Flatten the /app/extra hierarchy to remove unnecessary files
> Revert Wayland changes and add additional permissions

- com.slack.Slack.json
It seems that the release-notes page[1] is more up-to-date than the download page[2] for the Linux client. Use that instead as source for checking if new releases are available.
Fixes #218
[1]: https://slack.com/intl/en-gb/release-notes/linux
[2]: https://slack.com/intl/en-gb/downloads/linux
> Check for new releases in Slack release-notes page

- com.slack.Slack.appdata.xml
This should fix the issues FlatHub had with "Just the app window" since the original screenshot had two white bars at the bottom.
> Update app screenshot from https://slack.com/downloads/linux

- README.md
- com.slack.Slack.json
- slack.sh
Slack is not currently in a state where Wayland by default is
acceptable, see #212.
Allow the user to enable the Wayland socket if they are willing to
accept the feature incomplete window decorations, and other issues.
Notably enabling Wayland fixes the app looking blurry when running
under XWayland.
Also fixes the cursor being cut in half when running Slack with Wayland.
> Default to using X11, leave an opt in for users that want to use Wayland

- com.slack.Slack.metainfo.xml
- com.slack.Slack.yaml
xdg-desktop-portal is killing Slack on startup after around 5 seconds, it appears to be related to the following issue:
https://github.com/flatpak/xdg-desktop-portal/issues/1010
According to the desktop entry spec, if this is absent reasonable handling is up to implementations, so it'll use StartupWMClass instead to track the application startup.
Fixes: #251
Test: Disable running in background for Slack, observe as app does
not get closed by xdg-desktop-portal.
> Fix crashing due to background permissions, add lsb_release for debugging, update Slack to 4.36.140

- slack.sh
Flatpak seems to be setting `${WAYLAND_DISPLAY}` to an absolute path in some systems. This was causing the wayland check to fail because we were looking for the wrong path. This change should support all cases now.
> Fix wayland detection in some systems

- com.slack.Slack.metainfo.xml
Main color is taken from https://brand.slackhq.com/color the lighter variant is taken from one of the illustrations on that page.
Should look something like this later
Did this by using https://brand-color-preview.vercel.app/
> Adds branding colors

- com.slack.Slack.yaml
The versions of the stable and beta channel are finally alligned so we can switch without logging users out.
> Switch to the snap stable channel

- com.slack.Slack.yaml
> Fix window decoration icon in KDE when in native Wayland mode

- com.slack.Slack.yaml
DEs such as Gnome and KDE allow to configure desktop notifications per-application. To enable that, the following line should be present in the `.desktop` file:
```
X-GNOME-UsesNotifications=true
```
See https://developer.gnome.org/documentation/tutorials/notifications.html#disabling-notifications
> Enable fine grained control over notifications
